# Generated by Django 3.2.6 on 2021-08-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='tickets_1',
        ),
        migrations.AddField(
            model_name='concert',
            name='content',
            field=models.TextField(default='Content Goes Here'),
        ),
    ]
