# Generated by Django 3.2.6 on 2021-08-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_auto_20210812_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='doors',
            field=models.TimeField(default='19:30:00'),
            preserve_default=False,
        ),
    ]
