# Generated by Django 3.2.6 on 2021-08-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0004_concert_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
