# Generated by Django 3.2.6 on 2021-09-15 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(default='Artist', max_length=200)),
                ('date_one', models.DateField()),
                ('content', models.TextField(default='Content Goes Here')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_by', models.CharField(default='Shane Connaughton', max_length=200)),
                ('artist_website', models.URLField(blank=True, max_length=1024, null=True)),
                ('slug', models.SlugField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_one'],
            },
        ),
    ]
